id = "umka"
name = "Umka"
version = "0.0.1"
schema_version = 1
authors = ["Skejeton <contact@ske.land>"]
description = "Adds support for the Umka programming language"
repository = "https://github.com/skejeton/zed-umka"

[grammars.umka]
commit = "5020c9f43c6f0911ee705fed18150d6a829ba1b0"
repository = "https://github.com/skejeton/tree-sitter-umka"
