id = "umka"
name = "Umka"
version = "0.0.1"
schema_version = 1
authors = ["Skejeton <contact@ske.land>"]
description = "Adds support for the Umka programming language"
repository = "https://github.com/skejeton/zed-umka"

[grammars.umka]
commit = "d164af5bcda71cb7817d2c7f4beb61aac4fcf27e"
repository = "https://github.com/thacuber2a03/tree-sitter-umka"
