name = "Umka"
grammar = "umka"
path_suffixes = ["um"]
line_comments = ["// "]
block_comment = ["/* ", " */"]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
]
